[package]
name = "linkedin_module"
type = "contract"
authors = ["Vedant Chainani <vedantchainani1084@gmail.com>"]
compiler_version = ">=0.35.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.57.0", directory = "noir-projects/aztec-nr/aztec" }
passport = { path = "../../passport" }
noir_social_verify = { tag = "v0.0.3", git = "https://github.com/Envoy-VC/noir_social_verify", directory = "lib" }