[package]
name = "twitter_verify"
type = "bin"
authors = [""]
compiler_version = ">=0.35.0"

[dependencies]
rsa = { tag = "v0.3.1", git = "https://github.com/noir-lang/noir_rsa", directory = "lib" }
string_search = { tag = "v0.2.0", git = "https://github.com/noir-lang/noir_string_search" }
