[package]
name = "balances_email"
type = "contract"
authors = [""]
compiler_version = ">=0.35.0"

[dependencies]
compressed_string = {git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.60.0", directory="noir-projects/aztec-nr/compressed-string"}
aztec = {git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.60.0", directory="noir-projects/aztec-nr/aztec"}
zkemail = { tag = "v0.3.2", git = "https://github.com/zkemail/zkemail.nr", directory = "lib" }
noir_base64 = { tag = "v0.2.3", git = "https://github.com/noir-lang/noir_base64" }
token_contract = {git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.60.0", directory="noir-projects/noir-contracts/contracts/token_contract"}