[package]
name = "balance_module"
type = "contract"
authors = ["Vedant Chainani <vedantchainani1084@gmail.com>"]
compiler_version = ">=0.35.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.57.0", directory = "noir-projects/aztec-nr/aztec" }
passport = { path = "../../passport" }
token_portal_content_hash_lib = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.57.0", directory = "noir-projects/noir-contracts/contracts/token_portal_content_hash_lib" }
