[package]
name = "blocksense_historic_data_feed_store"
type = "contract"
authors = ["Nikolay Kostadinov <nikolaykostadinov21@gmail.com>"]
compiler_version = ">=0.34.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "aztec-packages-v0.55.1", directory = "noir-projects/aztec-nr/aztec" }
