[package]
name = "vc_module"
type = "contract"
authors = ["Vedant Chainani <vedantchainani1084@gmail.com>"]
compiler_version = ">=0.35.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.57.0", directory = "noir-projects/aztec-nr/aztec" }
passport = { path = "../../passport" }
json = { tag = "v0.2.0", git = "https://github.com/noir-lang/noir_json_parser" }
noir_jwt = { tag = "v1.0.0", git = "https://github.com/Envoy-VC/noir_jwt" }
