[package]
name = "schnorr_account_contract"
authors = ["Nikolay Kostadinov <nikolaykostadinov21@gmail.com>"]
compiler_version = ">=0.35.0"
type = "contract"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "aztec-packages-v0.57.0", directory = "noir-projects/aztec-nr/aztec" }
authwit = { git = "https://github.com/AztecProtocol/aztec-packages", tag = "aztec-packages-v0.57.0", directory = "noir-projects/aztec-nr/authwit" }
