[package]
name = "helper_witness_membership_getter"
type = "contract"
authors = ["skaunov"]
compiler_version = ">=0.34.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.57.0", directory="noir-projects/aztec-nr/aztec"}