[package]
name = "had_valid"
type = "bin"
authors = ["skaunov"]
compiler_version = ">=0.34.0"

[dependencies]
protocol_types = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.57.0", directory="noir-projects/noir-protocol-circuits/crates/types"}
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.57.0", directory="noir-projects/aztec-nr/aztec"}
nft_contract = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.57.0", directory="noir-projects/noir-contracts/contracts/nft_contract"}