blockheader_serd = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
contract_address_as_field = ""
low_nullifier_membership_witness_serd = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
nonce = ""
note_content = ["", "", ""]
nsk_m = ["", ""]
storage_slot = ""
witness_membership_serd = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
